### ISSUE TITLE
Blacklist check doesn't work

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/Word-Add-in-JS-SpecKit#6]
Nothing  happens when user clicks the Blacklist menu item on either the ribbon or the right-click menu.

**Comment by MIchaelMainer** [comment]
Sorry it took us so long to respond. We will try to verify/reproduce that issue and respond here very soon. @siewmoi since she worked on this.

**Comment by Rick-Kirkham** [comment]
This appears to be fixed.

**Comment by siewmoi** [comment]
Yes, I've fixed this.  It stopped working due to v1.3 API change.
