### ISSUE TITLE
obsolete code in validation.js

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/Word-Add-in-JS-SpecKit#7]
The code in validation.js assumes that the dialog can trigger just one event: DialogEventReceived and that you have to test the args.type property to tell if the event is a message received or some other event. This is no longer the way it works. There is now a separate DialogMessageReceived event. Testing arg.type in a handler for DialogEventReceived is pointless, because the arg.type is now always "dialogEventReceived".

**Comment by MIchaelMainer** [comment]
Sorry it took us so long to respond. We will try to verify/reproduce that issue and respond here very soon. @siewmoi since she worked on this.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
