### ISSUE TITLE
requireHTTPS option in validation.js is obsolete

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/Word-Add-in-JS-SpecKit#8]
The option **`requireHTTPs: true`** should be removed from the dialog options object in the call of displayDialogAsync. There no longer is a requireHTTPS option (because HTTPS is always required).

**Comment by MIchaelMainer** [comment]
Sorry it took us so long to respond. We will try to verify/reproduce that issue and respond here very soon. @siewmoi since she worked on this.

**Comment by Rick-Kirkham** [comment]
Looks like this was fixed.

**Comment by siewmoi** [comment]
Yes, I've fixed this.
